import './globals.css';
import HeaderViewSwitcher from './components/HeaderViewSwitcher';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  icons: {
    icon: [
      { url: '/svg/logo_icon.svg', type: 'image/svg+xml' }, 
    ],
    apple: '/svg/logo-icon-180x180.png', 
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" type="image/svg+xml" href="/svg/logo_icon.svg" />
      </head>
      <body>
        <HeaderViewSwitcher />
        {children}
      </body>
    </html>
  );
}
